### ISSUE TITLE
Helm chart should create the PVC

### ISSUE THREAD

**Issue by braunsonm** [F5Networks/f5-ipam-controller#100] opened 2022-03-09 16:55 UTC
#### Title
The Helm chart requires you pre-create the PVC. It should have an option to make this as part of the deployment.

#### Additional context
When using a tool like Terraform with Rancher you do not have the option of creating a PV but you can install helm charts. It makes it difficult to deploy this chart without also creating the PVC for you.

**Comment by trinaths** [comment] 2022-03-09 17:12
Duplicate of https://github.com/F5Networks/f5-ipam-controller/issues/96 

closing this issue.

**Closed by trinaths** 2022-03-09 17:12 UTC
